import type { Category } from "./types";

const NYC = "data.cityofnewyork.us";

/**
 * Curated meta-maps. Each clubs one or more underlying datasets
 * into a single visual layer. Every dataset id has been verified
 * against the Socrata GeoJSON endpoint (or GBFS) by
 * scripts/verify-datasets.ts.
 *
 * MTA subway/bus route geometry requires a separate GTFS adapter and
 * will be wired in once that lands.
 */

export const CATEGORIES: Category[] = [
  // ───────── Transit ─────────
  {
    id: "bike-network",
    name: "Bike Network",
    theme: "transit",
    icon: "Bicycle",
    description: "NYC DOT bike lanes, paths, and shared streets.",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "mzxg-pwib", limit: 30000 }],
    paint: { color: "#34d399", width: 1.8, opacity: 0.9 },
    popup: {
      title: "street",
      fields: [
        { key: "tf_facilit", label: "Facility" },
        { key: "lanecount", label: "Lanes" },
        { key: "fromstreet", label: "From" },
        { key: "tostreet", label: "To" },
        { key: "gwsystem", label: "Greenway System" },
        { key: "instdate", label: "Installed" },
      ],
    },
  },
  {
    id: "citi-bike",
    name: "Citi Bike Stations",
    theme: "transit",
    icon: "Lightning",
    description: "Live Citi Bike station locations from the GBFS feed.",
    kind: "points",
    datasets: [
      { protocol: "gbfs", url: "https://gbfs.citibikenyc.com/gbfs/en/station_information.json" },
    ],
    paint: { color: "#06b6d4", radius: 3, haloColor: "#062436" },
    popup: {
      title: "name",
      fields: [{ key: "capacity", label: "Capacity" }],
    },
  },
  {
    id: "bus-shelters",
    name: "Bus Stop Shelters",
    theme: "transit",
    icon: "Bus",
    description: "MTA bus stop shelters citywide.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "t4f2-8md7", limit: 5000 }],
    paint: { color: "#60a5fa", radius: 2.5, haloColor: "#0b1220" },
    popup: {
      title: "{on_street} & {cross_stre}",
      fields: [
        { key: "corner", label: "Corner" },
        { key: "boro_name", label: "Borough" },
        { key: "ntaname", label: "Neighborhood" },
        { key: "shelter_id", label: "Shelter ID" },
      ],
    },
  },
  {
    id: "bus-lanes",
    name: "Bus Lanes",
    theme: "transit",
    icon: "Bus",
    description: "Dedicated bus lanes on local streets.",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ycrg-ses3", limit: 5000 }],
    paint: { color: "#a78bfa", width: 2, opacity: 0.85 },
    popup: {
      title: "street",
      fields: [
        { key: "lane_type1", label: "Lane Type" },
        { key: "lane_color", label: "Color" },
        { key: "hours", label: "Hours" },
        { key: "days", label: "Days" },
        { key: "sbs_route1", label: "Route" },
        { key: "facility", label: "Facility" },
      ],
    },
  },
  {
    id: "parking-meters",
    name: "Parking Meters",
    theme: "transit",
    icon: "MapPin",
    description: "ParkNYC metered parking locations.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "693u-uax6", limit: 30000 }],
    paint: { color: "#818cf8", radius: 2, haloColor: "#1e1b4b" },
    popup: {
      title: "on_street",
      fields: [
        { key: "meter_hours", label: "Hours" },
        { key: "status", label: "Status" },
        { key: "from_street", label: "From" },
        { key: "to_street", label: "To" },
        { key: "side_of_street", label: "Side" },
        { key: "borough", label: "Borough" },
        { key: "pay_by_cell_number", label: "Pay-by-Cell #" },
      ],
    },
  },
  {
    id: "truck-routes",
    name: "Truck Routes",
    theme: "transit",
    icon: "Bus",
    description: "Designated truck route network across NYC.",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "jjja-shxy", limit: 5000 }],
    paint: { color: "#94a3b8", width: 1.5, opacity: 0.7 },
    popup: {
      title: "street",
      fields: [
        { key: "routetype", label: "Route Type" },
        { key: "truckroute", label: "Truck Route" },
        { key: "boroname", label: "Borough" },
        { key: "restrictio", label: "Restrictions" },
        { key: "nyc_reg", label: "Regulation" },
      ],
    },
  },
  {
    id: "bike-shelters",
    name: "Bicycle Parking Shelters",
    theme: "transit",
    icon: "Bicycle",
    description: "Covered bike parking shelters.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "dimy-qyej", limit: 2000 }],
    paint: { color: "#2dd4bf", radius: 3, haloColor: "#042f2e" },
    popup: {
      title: "location",
      fields: [
        { key: "street", label: "Street" },
        { key: "build_date", label: "Built" },
        { key: "boro_name", label: "Borough" },
        { key: "ntaname", label: "Neighborhood" },
        { key: "shelter_id", label: "Shelter ID" },
      ],
    },
  },
  {
    id: "rt-passenger-signs",
    name: "Real-Time Bus Signs",
    theme: "transit",
    icon: "Bus",
    description: "MTA real-time passenger information sign locations.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "g9jx-npbk", limit: 5000 }],
    paint: { color: "#7dd3fc", radius: 2.5, haloColor: "#082f49" },
    popup: {
      title: "stopname",
      fields: [
        { key: "routes", label: "Routes" },
        { key: "direction", label: "Direction" },
        { key: "corner", label: "Corner" },
        { key: "boroname", label: "Borough" },
        { key: "ntaname", label: "Neighborhood" },
      ],
    },
  },
  {
    id: "pedestrian-ramps",
    name: "Pedestrian Ramps",
    theme: "transit",
    icon: "MapPin",
    description: "ADA pedestrian ramp locations.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "ufzp-rrqu", limit: 30000 }],
    paint: { color: "#cbd5e1", radius: 1.6, haloColor: "#0f172a" },
    popup: {
      title: "ramp_onstr",
      fields: [
        { key: "dws_conditions", label: "Detectable Surface" },
        { key: "ramp_width", label: "Width (in)" },
        { key: "ramp_length", label: "Length (in)" },
        { key: "ramp_running_slope_total", label: "Slope (%)" },
        { key: "obstacles_ramp", label: "Obstacles" },
        { key: "ponding", label: "Ponding" },
      ],
    },
  },
  {
    id: "escooter-parking",
    name: "E-Scooter Parking",
    theme: "transit",
    icon: "Bicycle",
    description: "Shared e-scooter parking corrals.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "hjz2-y62k", limit: 5000 }],
    paint: { color: "#22d3ee", opacity: 0.35 },
    popup: {
      title: "parking_location",
      fields: [
        { key: "type", label: "Type" },
        { key: "borough", label: "Borough" },
        { key: "install_da", label: "Installed" },
      ],
    },
  },
  {
    id: "sidewalk-cafes",
    name: "Sidewalk Cafes",
    theme: "transit",
    icon: "ForkKnife",
    description: "Permitted sidewalk cafes (line geometry along the sidewalk).",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ptd9-4c6m", limit: 5000 }],
    paint: { color: "#fb7185", width: 2, opacity: 0.9 },
  },

  // ───────── Nature & Parks ─────────
  {
    id: "trees",
    name: "Tree Maps",
    theme: "nature",
    icon: "Tree",
    description:
      "Every street tree NYC tracks. Forestry tree points and planting spaces clubbed together.",
    kind: "points",
    cluster: true,
    datasets: [
      { protocol: "socrata", domain: NYC, id: "hn5i-inap", limit: 50000 },
      { protocol: "socrata", domain: NYC, id: "82zj-84is", limit: 30000 },
    ],
    paint: { color: "#22c55e", radius: 1.8, haloColor: "#052012" },
    popup: {
      title: "genusspecies",
      fields: [
        { key: "dbh", label: "Diameter (in)" },
        { key: "tpcondition", label: "Condition" },
        { key: "tpstructure", label: "Structure" },
        { key: "parkname", label: "Park" },
        { key: "streetname", label: "Street" },
      ],
    },
  },
  {
    id: "parks",
    name: "Parks & Green Space",
    theme: "nature",
    icon: "Park",
    description: "NYC Parks properties: every park and natural area.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "enfh-gkve", limit: 5000 }],
    paint: { color: "#22c55e", opacity: 0.18 },
  },
  {
    id: "playgrounds",
    name: "Playgrounds & Recreation",
    theme: "nature",
    icon: "Park",
    description: "NYC Parks active and passive recreation areas.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "kcqe-vnci", limit: 5000 }],
    paint: { color: "#84cc16", opacity: 0.18 },
  },
  {
    id: "beaches",
    name: "Beaches",
    theme: "nature",
    icon: "Park",
    description: "NYC public beaches.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ijwa-mn2v", limit: 200 }],
    paint: { color: "#fde68a", opacity: 0.4 },
  },
  {
    id: "pools",
    name: "Pools",
    theme: "nature",
    icon: "Park",
    description: "NYC Parks public pools.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "y5rm-wagw", limit: 200 }],
    paint: { color: "#5eead4", opacity: 0.5 },
  },
  {
    id: "wetlands",
    name: "Wetlands",
    theme: "nature",
    icon: "Drop",
    description: "NYC mapped wetland areas.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "p48c-iqtu", limit: 5000 }],
    paint: { color: "#10b981", opacity: 0.3 },
  },
  {
    id: "forever-wild",
    name: "Forever Wild Areas",
    theme: "nature",
    icon: "Tree",
    description: "Forever Wild nature preserves.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "48va-85tp", limit: 500 }],
    paint: { color: "#16a34a", opacity: 0.3 },
  },
  {
    id: "community-gardens",
    name: "Community Gardens",
    theme: "nature",
    icon: "Park",
    description: "GreenThumb community garden parcels.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "p78i-pat6", limit: 2000 }],
    paint: { color: "#a3e635", opacity: 0.35 },
  },

  // ───────── Buildings & Land ─────────
  {
    id: "landmarks",
    name: "Landmarks",
    theme: "buildings",
    icon: "Buildings",
    description: "Designated and calendared individual landmark buildings & sites.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ncre-qhxs", limit: 5000 }],
    paint: { color: "#a78bfa", radius: 3, haloColor: "#1e1140" },
    popup: {
      title: "lm_name",
      fields: [
        { key: "lm_type", label: "Type" },
        { key: "desig_addr", label: "Address" },
        { key: "desdate", label: "Designated" },
        { key: "boroughid", label: "Borough" },
        { key: "status", label: "Status" },
      ],
    },
  },
  {
    id: "historic-districts",
    name: "Historic Districts",
    theme: "buildings",
    icon: "Buildings",
    description: "Landmarked historic districts citywide.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "skyk-mpzq", limit: 1000 }],
    paint: { color: "#c4b5fd", opacity: 0.18 },
    popup: {
      title: "area_name",
      fields: [
        { key: "status_of_", label: "Status" },
        { key: "desdate", label: "Designated" },
        { key: "last_actio", label: "Last Action" },
        { key: "borough", label: "Borough" },
        { key: "lp_number", label: "LP Number" },
      ],
    },
  },
  {
    id: "pops",
    name: "Privately Owned Public Spaces",
    theme: "buildings",
    icon: "Buildings",
    description: "POPS: privately owned spaces open to the public.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "rvih-nhyn", limit: 1000 }],
    paint: { color: "#818cf8", radius: 3.2, haloColor: "#1e1b4b" },
    popup: {
      title: "building_name",
      fields: [
        { key: "public_space_type", label: "Type" },
        { key: "building_address_with_zip", label: "Address" },
        { key: "year_completed", label: "Year Completed" },
        { key: "hour_of_access_required", label: "Access Hours" },
        { key: "physically_disabled", label: "Accessible" },
      ],
    },
  },
  {
    id: "waterfront-access",
    name: "Waterfront Public Access",
    theme: "buildings",
    icon: "Drop",
    description: "Required waterfront public access areas (WPAAs).",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "388s-pnvc", limit: 2000 }],
    paint: { color: "#7dd3fc", opacity: 0.3 },
    popup: {
      title: "name",
      fields: [
        { key: "waterway", label: "Waterway" },
        { key: "status", label: "Status" },
        { key: "hours_open", label: "Hours" },
        { key: "maintenanc", label: "Maintained By" },
        { key: "wpaa_area", label: "Area (sqft)" },
      ],
    },
  },
  {
    id: "vacant-storefronts",
    name: "Vacant Storefronts",
    theme: "buildings",
    icon: "Storefront",
    description: "Storefronts reported vacant in DOF surveys.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "92iy-9c3n", limit: 10000 }],
    paint: { color: "#e11d48", radius: 2.5, haloColor: "#3f0a1a" },
    popup: {
      title: "property_street_address_or",
      fields: [
        { key: "primary_business_activity", label: "Last Business" },
        { key: "vacant_on_12_31", label: "Vacant" },
        { key: "nbhd", label: "Neighborhood" },
        { key: "borough_1", label: "Borough" },
        { key: "reporting_year", label: "Reporting Year" },
      ],
    },
  },
  {
    id: "nycha",
    name: "NYCHA Developments",
    theme: "buildings",
    icon: "Buildings",
    description: "NYC Housing Authority public housing developments.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "phvi-damg", limit: 1000 }],
    paint: { color: "#9333ea", opacity: 0.25 },
    popup: {
      title: "developmen",
      fields: [
        { key: "borough", label: "Borough" },
        { key: "tds_num", label: "TDS Number" },
      ],
    },
  },
  {
    id: "dob-coo",
    name: "DOB Certificates of Occupancy",
    theme: "buildings",
    icon: "Buildings",
    description: "Recently issued DOB Certificates of Occupancy.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "bs8b-p36w", limit: 10000 }],
    paint: { color: "#d946ef", radius: 2, haloColor: "#1f0a24" },
    popup: {
      title: "{house_number} {street_name}",
      fields: [
        { key: "c_o_issue_date", label: "Issued" },
        { key: "issue_type", label: "Issue Type" },
        { key: "job_type", label: "Job Type" },
        { key: "application_status_raw", label: "Status" },
        { key: "borough", label: "Borough" },
        { key: "postcode", label: "ZIP" },
      ],
    },
  },

  // ───────── Civic & Boundaries ─────────
  {
    id: "boroughs",
    name: "Boroughs",
    theme: "civic",
    icon: "MapTrifold",
    description: "The five borough boundaries.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "gthc-hcne", limit: 10 }],
    paint: { color: "#f472b6", opacity: 0.06 },
    popup: {
      title: "boroname",
      fields: [{ key: "borocode", label: "Borough Code" }],
    },
  },
  {
    id: "neighborhoods",
    name: "Neighborhoods",
    theme: "civic",
    icon: "MapPinArea",
    description: "Neighborhood Tabulation Areas (NTAs).",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "9nt8-h7nd", limit: 500 }],
    paint: { color: "#fbcfe8", opacity: 0.06 },
    popup: {
      title: "ntaname",
      fields: [
        { key: "boroname", label: "Borough" },
        { key: "cdtaname", label: "Community District" },
        { key: "nta2020", label: "NTA Code" },
      ],
    },
  },
  {
    id: "council-districts",
    name: "Council Districts",
    theme: "civic",
    icon: "Bank",
    description: "NYC City Council districts.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "872g-cjhh", limit: 100 }],
    paint: { color: "#fb7185", opacity: 0.07 },
  },
  {
    id: "zip-codes",
    name: "ZIP Codes",
    theme: "civic",
    icon: "MapTrifold",
    description: "Modified ZIP code tabulation areas (MODZCTA).",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "pri4-ifjk", limit: 500 }],
    paint: { color: "#ec4899", opacity: 0.06 },
  },
  {
    id: "census-tracts",
    name: "Census Tracts (2020)",
    theme: "civic",
    icon: "MapTrifold",
    description: "2020 US Census tract boundaries for NYC.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "63ge-mke6", limit: 3000 }],
    paint: { color: "#f9a8d4", opacity: 0.05 },
  },
  {
    id: "community-boards",
    name: "Community Boards",
    theme: "civic",
    icon: "Bank",
    description: "NYC community board offices.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ruf7-3wgc", limit: 100 }],
    paint: { color: "#fda4af", radius: 4, haloColor: "#3f0a1a" },
    popup: {
      title: "community_board",
      fields: [
        { key: "neighborhoods", label: "Neighborhoods" },
        { key: "cb_chair", label: "Chair" },
        { key: "cb_district_manager", label: "District Manager" },
        { key: "cb_office_phone", label: "Phone" },
        { key: "cb_office_email", label: "Email" },
        { key: "cb_board_meeting", label: "Board Meeting" },
      ],
    },
  },
  {
    id: "congressional-districts",
    name: "Congressional Districts",
    theme: "civic",
    icon: "Bank",
    description: "US Congressional districts covering NYC.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "j3u5-usz2", limit: 50 }],
    paint: { color: "#f87171", opacity: 0.06 },
  },
  {
    id: "state-senate",
    name: "State Senate Districts",
    theme: "civic",
    icon: "Bank",
    description: "NY State Senate districts.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "afns-vxeu", limit: 100 }],
    paint: { color: "#dc2626", opacity: 0.06 },
  },
  {
    id: "state-assembly",
    name: "State Assembly Districts",
    theme: "civic",
    icon: "Bank",
    description: "NY State Assembly districts.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "5yfv-9hkp", limit: 200 }],
    paint: { color: "#ea580c", opacity: 0.06 },
  },
  {
    id: "election-districts",
    name: "Election Districts",
    theme: "civic",
    icon: "Bank",
    description: "Voter election districts.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "wwxk-38u4", limit: 5000 }],
    paint: { color: "#fb923c", opacity: 0.05 },
  },
  {
    id: "bids",
    name: "Business Improvement Districts",
    theme: "civic",
    icon: "Storefront",
    description: "BIDs: geographically defined business improvement districts.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "7jdm-inj8", limit: 200 }],
    paint: { color: "#c026d3", opacity: 0.18 },
    popup: {
      title: "f_all_bi_2",
      fields: [
        { key: "f_all_bi_1", label: "Borough" },
        { key: "year_found", label: "Founded" },
        { key: "f_all_bi_4", label: "Website" },
      ],
    },
  },

  // ───────── Public Safety ─────────
  {
    id: "police-precincts",
    name: "Police Precincts",
    theme: "safety",
    icon: "ShieldStar",
    description: "NYPD precinct boundaries.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "y76i-bdw7", limit: 100 }],
    paint: { color: "#0ea5e9", opacity: 0.07 },
  },
  {
    id: "crashes",
    name: "Motor Vehicle Crashes",
    theme: "safety",
    icon: "ShieldStar",
    description: "Recent NYPD-reported motor vehicle collisions (sampled).",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "h9gi-nx95", limit: 20000 }],
    paint: { color: "#ef4444", radius: 2, haloColor: "#3f0a0a" },
    popup: {
      title: "{on_street_name}",
      fields: [
        { key: "crash_date", label: "Date" },
        { key: "crash_time", label: "Time" },
        { key: "number_of_persons_injured", label: "Injured" },
        { key: "number_of_persons_killed", label: "Killed" },
        { key: "contributing_factor_vehicle_1", label: "Cause" },
        { key: "vehicle_type_code1", label: "Vehicle" },
        { key: "borough", label: "Borough" },
      ],
    },
  },
  {
    id: "speed-humps",
    name: "Speed Humps",
    theme: "safety",
    icon: "ShieldStar",
    description: "Vision Zero speed hump installations.",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "jknp-skuy", limit: 5000 }],
    paint: { color: "#f59e0b", width: 1.6, opacity: 0.9 },
  },
  {
    id: "slow-zones",
    name: "Neighborhood Slow Zones",
    theme: "safety",
    icon: "ShieldStar",
    description: "Vision Zero neighborhood slow zones.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "bqye-aqft", limit: 200 }],
    paint: { color: "#facc15", opacity: 0.18 },
  },
  {
    id: "speed-limits",
    name: "Speed Limits",
    theme: "safety",
    icon: "ShieldStar",
    description: "Vision Zero posted speed limit segments.",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "5mad-ntua", limit: 10000 }],
    paint: { color: "#fb923c", width: 1.4, opacity: 0.7 },
  },
  {
    id: "pedestrian-demand",
    name: "Pedestrian Demand",
    theme: "safety",
    icon: "ShieldStar",
    description: "Pedestrian Mobility Plan demand corridors.",
    kind: "lines",
    datasets: [{ protocol: "socrata", domain: NYC, id: "fwpa-qxaf", limit: 5000 }],
    paint: { color: "#7c3aed", width: 1.6, opacity: 0.8 },
  },
  {
    id: "vision-zero-base",
    name: "Vision Zero Base Reports",
    theme: "safety",
    icon: "ShieldStar",
    description: "Vision Zero baseline reporting points.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ph7v-u5f3", limit: 5000 }],
    paint: { color: "#6366f1", radius: 2.5, haloColor: "#1e1b4b" },
  },

  // ───────── Health ─────────
  {
    id: "restaurants",
    name: "Restaurant Inspections",
    theme: "health",
    icon: "ForkKnife",
    description: "Most recent NYC restaurant inspection locations.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "43nn-pn8j", limit: 20000 }],
    paint: { color: "#fb923c", radius: 2, haloColor: "#241201" },
    popup: {
      title: "dba",
      fields: [
        { key: "cuisine_description", label: "Cuisine" },
        { key: "grade", label: "Grade" },
        { key: "score", label: "Score" },
        { key: "inspection_date", label: "Inspected" },
        { key: "violation_description", label: "Last Violation" },
        { key: "phone", label: "Phone" },
      ],
    },
  },
  {
    id: "health-center-districts",
    name: "Health Center Districts",
    theme: "health",
    icon: "Heartbeat",
    description: "DOH health center service districts.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "6ez8-za84", limit: 200 }],
    paint: { color: "#fca5a5", opacity: 0.12 },
  },
  {
    id: "health-areas",
    name: "Health Areas",
    theme: "health",
    icon: "Heartbeat",
    description: "DOHMH health areas.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "jntv-ngw5", limit: 500 }],
    paint: { color: "#fb7185", opacity: 0.1 },
  },
  {
    id: "syringe-dropoff",
    name: "Pharma & Syringe Drop-Off",
    theme: "health",
    icon: "Heartbeat",
    description: "Pharmaceutical and syringe disposal locations.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "edk2-vkjh", limit: 1000 }],
    paint: { color: "#ef4444", radius: 2.8, haloColor: "#3f0a0a" },
  },
  {
    id: "parks-syringe",
    name: "Parks Syringe Disposal Kiosks",
    theme: "health",
    icon: "Heartbeat",
    description: "Syringe disposal kiosks in NYC parks.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "r465-fr2q", limit: 500 }],
    paint: { color: "#dc2626", radius: 2.8, haloColor: "#1f0a0a" },
  },
  {
    id: "litter-baskets",
    name: "DSNY Litter Baskets",
    theme: "health",
    icon: "Heartbeat",
    description: "DSNY litter basket inventory.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "8znf-7b2c", limit: 30000 }],
    paint: { color: "#a16207", radius: 1.6, haloColor: "#1c1101" },
  },
  {
    id: "rodent-inspections",
    name: "Rodent Inspections",
    theme: "health",
    icon: "Heartbeat",
    description: "DOHMH rodent inspection results (sampled).",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "p937-wjvj", limit: 20000 }],
    paint: { color: "#7f1d1d", radius: 1.6, haloColor: "#0a0606" },
  },

  // ───────── Education ─────────
  {
    id: "schools",
    name: "Public Schools",
    theme: "education",
    icon: "GraduationCap",
    description: "NYC DOE public school point locations.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "a3nt-yts4", limit: 5000 }],
    paint: { color: "#facc15", radius: 3, haloColor: "#241c02" },
  },
  {
    id: "libraries",
    name: "Libraries",
    theme: "education",
    icon: "Bank",
    description: "Public library locations across NYC.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "feuq-due4", limit: 1000 }],
    paint: { color: "#fcd34d", radius: 3.2, haloColor: "#1f1700" },
  },
  {
    id: "school-zones-elem",
    name: "Elementary School Zones",
    theme: "education",
    icon: "GraduationCap",
    description: "DOE elementary school attendance zones (2024-25).",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "cmjf-yawu", limit: 2000 }],
    paint: { color: "#fbbf24", opacity: 0.1 },
  },
  {
    id: "school-zones-middle",
    name: "Middle School Zones",
    theme: "education",
    icon: "GraduationCap",
    description: "DOE middle school attendance zones (2024-25).",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "t26j-jbq7", limit: 2000 }],
    paint: { color: "#f59e0b", opacity: 0.1 },
  },
  {
    id: "school-zones-high",
    name: "High School Zones",
    theme: "education",
    icon: "GraduationCap",
    description: "DOE high school attendance zones (2024-25).",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ruu9-egea", limit: 2000 }],
    paint: { color: "#eab308", opacity: 0.1 },
  },
  {
    id: "school-districts",
    name: "School Districts",
    theme: "education",
    icon: "GraduationCap",
    description: "NYC DOE community school district boundaries.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "8ugf-3d8u", limit: 100 }],
    paint: { color: "#fde68a", opacity: 0.08 },
  },

  // ───────── Environment & Resilience ─────────
  {
    id: "flood-vulnerability",
    name: "Flood Vulnerability Index",
    theme: "environment",
    icon: "Drop",
    description: "NYC's Flood Vulnerability Index (FVI) by area.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "mrjc-v9pm", limit: 5000 }],
    paint: { color: "#3b82f6", opacity: 0.18 },
  },
  {
    id: "hurricane-evac",
    name: "Hurricane Evacuation Zones",
    theme: "environment",
    icon: "Drop",
    description: "OEM hurricane evacuation zones.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "epne-qv9x", limit: 2000 }],
    paint: { color: "#f97316", opacity: 0.18 },
  },
  {
    id: "sea-level-2050",
    name: "Sea Level Rise (2050s)",
    theme: "environment",
    icon: "Drop",
    description: "2050s mean sea level rise projection.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "8n8s-np59", limit: 2000 }],
    paint: { color: "#0891b2", opacity: 0.22 },
  },
  {
    id: "sea-level-2080",
    name: "Sea Level Rise (2080s)",
    theme: "environment",
    icon: "Drop",
    description: "2080s 100-year floodplain under sea level rise.",
    kind: "polygons",
    datasets: [{ protocol: "socrata", domain: NYC, id: "ek8y-fsqz", limit: 2000 }],
    paint: { color: "#1d4ed8", opacity: 0.22 },
  },
  {
    id: "air-quality",
    name: "Air Quality Sensors",
    theme: "environment",
    icon: "Drop",
    description: "Queens air quality sensor pilot deployments.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "2juy-aj8e", limit: 500 }],
    paint: { color: "#8b5cf6", radius: 4, haloColor: "#1e1140" },
  },
  {
    id: "green-infrastructure",
    name: "DEP Green Infrastructure",
    theme: "environment",
    icon: "Drop",
    description: "Bioswales, rain gardens, and other green infrastructure assets.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "df32-vzax", limit: 30000 }],
    paint: { color: "#16a34a", radius: 1.8, haloColor: "#052012" },
  },
  {
    id: "catch-basins",
    name: "Stormwater Catch Basins",
    theme: "environment",
    icon: "Drop",
    description: "DEP citywide stormwater catch basin inventory.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "2w2g-fk3i", limit: 30000 }],
    paint: { color: "#64748b", radius: 1.4, haloColor: "#0f172a" },
  },

  // ───────── Commerce / Civic Tech ─────────
  {
    id: "wifi",
    name: "Public Wifi & LinkNYC",
    theme: "commerce",
    icon: "WifiHigh",
    description: "Every free public wifi access point.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "yjub-udmw", limit: 10000 }],
    paint: { color: "#67e8f9", radius: 2.5, haloColor: "#062e36" },
  },
  {
    id: "linknyc",
    name: "LinkNYC Kiosks",
    theme: "commerce",
    icon: "WifiHigh",
    description: "LinkNYC kiosk live status.",
    kind: "points",
    cluster: true,
    datasets: [{ protocol: "socrata", domain: NYC, id: "n6c5-95xh", limit: 5000 }],
    paint: { color: "#06b6d4", radius: 2.5, haloColor: "#062436" },
  },
  {
    id: "newsstands",
    name: "Newsstands",
    theme: "commerce",
    icon: "Storefront",
    description: "Permitted newsstand locations.",
    kind: "points",
    datasets: [{ protocol: "socrata", domain: NYC, id: "w9zq-xm8b", limit: 1000 }],
    paint: { color: "#f59e0b", radius: 3, haloColor: "#241201" },
  },
];

export const CATEGORIES_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));
